- name: Setup load balance
  hosts: lb
  become: yes
  vars_files:
    - group_vars/all.yml
  pre_tasks:
    - name: install pymysql 2.7 3.0
      apt:
        name: "{{item}}"
        state: latest
      loop:
        - python3-pymysql
  roles:
    - varnish