- name: create db
  mysql_db:
    name: "{{magento_db_name}}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
- name: create user
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{magento_db_user}}"
    password: "{{magento_db_password}}"
    host: "{{magento_db_host}}"
    priv: "*.*:ALL"
    state: present
- name: add auth
  shell:
    cmd: "echo y | sudo composer global config http-basic.repo.magento.com {{public_key}} {{private_key}}"

#- name: create m2 project
#  shell:
#    cmd: "echo y | sudo composer create-project --repository=https://repo.magento.com/ magento/project-community-edition {{onlyDirName}}"
#    chdir: "/var/www/html"
- name: setup m2
  shell:
    cmd: "bin/magento setup:install --base-url={{base_url}} --db-host={{magento_db_host}} --db-name={{magento_db_name}} --db-user={{magento_db_user}} --db-password={{magento_db_password}} --admin-firstname=Admin --admin-lastname=User --admin-email=admin@example.com --admin-user={{admin_user}} --admin-password={{admin_password}} --language=en_US --currency=USD --timezone=America/Chicago --use-rewrites=1"
    chdir: "{{dir}}"
- name: "chmod {{dir}}"
  file:
    path: "{{dir}}"
    owner: "{{php_user}}"
    group: "{{php_group}}"
    mode: "1777"
    recurse: 1
    state: directory
- name: add to ect hosts
  lineinfile:
    path: "/etc/hosts"
    line: "127.0.0.1 {{domain_name}}"
- name: add nginx
  template:
    src: "../templates/ansible.demo.j2"
    dest: "/etc/nginx/sites-enabled/ansible.demo.conf"
- name: restart nginx
  service:
    name: nginx
    state: restarted