- name: "install library"
  apt:
    name:
      - debian-archive-keyring
      - curl
      - gnupg
      - apt-transport-https
    update-cache: yes
    state: latest
- name: "add varnish gpg key"
  shell: curl -L https://packagecloud.io/varnishcache/varnish41/gpgkey | sudo apt-key add -
- name: "update cache"
  apt:
    update-cache: yes
- name: "install varnish"
  apt:
    name: varnish
- name: add varnish
  template:
    src: "../templates/vcl_v4_config.j2"
    dest: "/etc/varnish/default.vcl"
- name: "Replace line in file varnish"
  become: yes
  replace:
    path: /etc/default/varnish
    regexp: 'DAEMON_OPTS=\"-a.+'
    replace: 'DAEMON_OPTS="-a: 80 /'
- name: "Replace line in file varnish"
  become: yes
  replace:
    path: /lib/systemd/system/varnish.service
    regexp: 'ExecStart=/usr/sbin/varnishd.+'
    replace: 'ExecStart=/usr/sbin/varnishd -a :80 -a localhost:6081,PROXY -p feature=+http2 -f /etc/varnish/default.vcl -s malloc,2g'
- name: "daemon reload"
  shell: "systemctl daemon-reload"
  become: true
- name: "restart varnish service"
  shell: "systemctl restart varnish"
  become: true